FROM openjdk:8-jdk-alpine
COPY target/management-processor-service-0.0.1-SNAPSHOT.jar management-processor-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/management-processor-service-0.0.1-SNAPSHOT.jar"]