FROM openjdk:8-jdk-alpine
COPY target/management-consumer-service-0.0.1-SNAPSHOT.jar management-consumer-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/management-consumer-service-0.0.1-SNAPSHOT.jar"]