FROM openjdk:8-jdk-alpine
COPY target/management-producer-consumer-service-0.0.1-SNAPSHOT.jar management-producer-consumer-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/management-producer-consumer-service-0.0.1-SNAPSHOT.jar"]